name: n_image_picker
description: Configurable and easy-to-use cross-platform image selector.
version: 3.3.2

homepage: https://github.com/nycm1989/nImagePicker
repository: https://github.com/nycm1989/nImagePicker

topics:
  - picker
  - image
  - preview
  - cross-platform

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"


dependencies:
  flutter:
    sdk: flutter
  file_picker: ^9.0.0
  http: ^1.2.0
  http_parser: ^4.0.2
  path_provider: ^2.1.3
  image: ^4.2.0
  web: ^1.1.0
  uuid: ^4.5.1
  dotted_decoration: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_lints: ^5.0.0

screenshots:
  - description: 'Loaded image screenshot'
    path: screens/2.png

acknowledgements:
  - Special thanks to [Moinkhan780](https://github.com/moinkhan780) for his contributions to version 2.3.2:
    - Fix setFromURL method.
    - Fixed typo mistakes in the code.
    - Optimized and updated the example code for better clarity and functionality.

# dart pub publish --dry-run