library n_image_picker_view;

import 'dart:async';
import 'package:flutter/material.dart';
import 'image_body.dart';

class ImageViewer extends ImageBody{
  ImageViewer({
    super.onTap,
    required String image,
    super.width,
    super.height,
    super.onErrorWidget,
    super.onLoadingWidget,
    super.margin,
    super.bankgroundColor,
    super.borderRadius,
    super.border,
    super.shadow,
    super.fit,
    super.shape,
    super.headers,
    super.key,
    super.tag,
    super.duration,
    super.maxSize,
  }) : super (
    onLoadingImage : image,
    readOnly       : true,
    filterOpacity  : 0,
    viewerBlur     : false
  );

  factory ImageViewer.square({
    Future<void> Function() ? onTap,
    required String           image,
    double                  ? dimension,
    Widget                  ? emptyWidget,
    Widget                  ? filledWidget,
    Widget                  ? onErrorWidget,
    Widget                  ? onLoadingWidget,
    EdgeInsetsGeometry      ? margin,
    Color                   ? bankgroundColor,
    BorderRadius            ? borderRadius,
    Border                  ? border,
    BoxShadow               ? shadow,
    BoxFit                  ? fit,
    Map<String, String>     ? headers,
    Object                  ? tag,
    Duration                ? duration,
    int                     ? maxSize,
  }) => ImageViewer(
    onTap             : onTap,
    image             : image,
    width             : dimension,
    height            : dimension,
    onErrorWidget     : onErrorWidget,
    onLoadingWidget   : onLoadingWidget,
    margin            : margin,
    bankgroundColor   : bankgroundColor,
    borderRadius      : borderRadius,
    border            : border,
    shadow            : shadow,
    fit               : fit??BoxFit.cover,
    shape             : BoxShape.rectangle,
    headers           : headers,
    tag               : tag,
    duration          : duration??Duration(milliseconds: 250),
    maxSize           : maxSize,
  );

  factory ImageViewer.circle({
    Future<void> Function() ? onTap,
    required String           image,
    double                  ? dimension,
    Widget                  ? emptyWidget,
    Widget                  ? filledWidget,
    Widget                  ? onErrorWidget,
    Widget                  ? onLoadingWidget,
    EdgeInsetsGeometry      ? margin,
    Color                   ? bankgroundColor,
    Border                  ? border,
    BoxShadow               ? shadow,
    BoxFit                  ? fit,
    Map<String, String>     ? headers,
    Object                  ? tag,
    Duration                ? duration,
    int                     ? maxSize,
  }) => ImageViewer(
    onTap             : onTap,
    image             : image,
    width             : dimension,
    height            : dimension,
    onErrorWidget     : onErrorWidget,
    onLoadingWidget   : onLoadingWidget,
    margin            : margin,
    bankgroundColor   : bankgroundColor,
    border            : border,
    shadow            : shadow,
    fit               : fit??BoxFit.cover,
    shape             : BoxShape.circle,
    headers           : headers,
    tag               : tag,
    duration          : duration??Duration(milliseconds: 250),
    maxSize           : maxSize,
  );

  factory ImageViewer.expand({
    Future<void> Function() ? onTap,
    required String           image,
    Widget                  ? emptyWidget,
    Widget                  ? filledWidget,
    Widget                  ? onErrorWidget,
    Widget                  ? onLoadingWidget,
    EdgeInsetsGeometry      ? margin,
    Color                   ? bankgroundColor,
    BorderRadius            ? borderRadius,
    Border                  ? border,
    BoxShadow               ? shadow,
    BoxFit                  ? fit,
    Map<String, String>     ? headers,
    Object                  ? tag,
    Duration                ? duration,
    int                     ? maxSize,
  }) => ImageViewer(
    onTap             : onTap,
    image             : image,
    width             : double.infinity,
    height            : double.infinity,
    onErrorWidget     : onErrorWidget,
    onLoadingWidget   : onLoadingWidget,
    margin            : margin,
    bankgroundColor   : bankgroundColor,
    borderRadius      : borderRadius,
    border            : border,
    shadow            : shadow,
    fit               : fit??BoxFit.cover,
    shape             : BoxShape.rectangle,
    headers           : headers,
    tag               : tag,
    duration          : duration??Duration(milliseconds: 250),
    maxSize           : maxSize,
  );
}